In [1]:
import sqlite3, pandas as pd

In [2]:
df = pd.read_csv('../../../B___Data/CSV/pokemons.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1150 entries, 0 to 1149
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nom_pkmn          1150 non-null   object
 1   nom_pkmn_us       1150 non-null   object
 2   num_pokedex       1150 non-null   int64
 3   url_image         1150 non-null   object
 4   url_cri           1150 non-null   object
 5   type_1            1150 non-null   object
 6   type_2            620 non-null    object
 7   taille_m          1145 non-null   object
 8   poids_kg          1150 non-null   object
 9   talent_1          1126 non-null   object
 10  talent_2          568 non-null    object
 11  talent_cache      898 non-null    object
 12  sexe              1150 non-null   object
 13  taux_de_capture   1036 non-null   float64
 14  cycle_eclosion    1037 non-null   float64
 15  groupe_oeuf_1     1037 non-null   object
 16  groupe_oeuf_2     286 non-null    object
 17  points_effort     1035 non-null   object
 18  points_exp        1037 non-null   object
 19  exp_niv100        1037 non-null   object
 20  pv                1117 non-null   float64
 21  attaque           1115 non-null   float64
 22  attaque_speciale  1115 non-null   float64
 23  defense           1115 non-null   float64
 24  defense_speciale  1119 non-null   float64
 25  vitesse           1119 non-null   float64
dtypes: float64(8), int64(1), object(17)
memory usage: 233.7+ KB

In [4]:
df[df.talent_1.isna()].sort_values(by='num_pokedex')

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
1080,Caninos,Growlithe,58,/images/thumb/e/e2/Caninos-RFVF.png/250px-Cani...,/images/e/e9/Cri_0058_HOME.ogg,Feu,NaN,"0,7","19,0",NaN,...,NaN,+1 Att,91 exp.,1 250 000 exp.,55.0,70.0,45.0,45.0,50.0,60.0
1058,Gravalanch,Graveler,75,/images/thumb/a/a5/Gravalanch-RFVF.png/250px-G...,/images/4/4a/Cri_0075_HOME.ogg,Roche,Sol,"1,0","105,0",NaN,...,NaN,+2 Déf.,134 exp.,1 059 860 exp.,55.0,95.0,115.0,115.0,45.0,35.0
810,Tengalice,Shiftry,275,/images/thumb/d/d2/Tengalice-RS.png/250px-Teng...,/images/1/1d/Cri_0275_HOME.ogg,Plante,Ténèbres,"1,3","59,6",NaN,...,Végétal,+3 Att.,181 exp.,1 059 860 exp.,90.0,100.0,60.0,60.0,60.0,80.0
675,Tiplouf,Piplup,393,/images/thumb/c/c2/Tiplouf-DEPS.png/250px-Tipl...,/images/8/84/Cri_0393_HOME.ogg,Eau,NaN,"0,4","5,2",NaN,...,Terrestre,+1 Att. Spé,66 exp.,1 059 860 exp.,53.0,51.0,53.0,53.0,56.0,40.0
674,Prinplouf,Prinplup,394,/images/thumb/c/c5/Prinplouf-DEPS.png/250px-Pr...,/images/2/27/Cri_0394_HOME.ogg,Eau,NaN,"0,8","23,0",NaN,...,Terrestre,+2 Att. Spé,143 exp.,1 059 860 exp.,64.0,66.0,68.0,68.0,76.0,50.0
673,Pingoléon,Empoleon,395,/images/thumb/1/14/Pingol%C3%A9on-DEPS.png/250...,/images/9/95/Cri_0395_HOME.ogg,Eau,Acier,"1,7","84,5",NaN,...,Terrestre,+3 Att. Spé,210 exp.,1 059 860 exp.,84.0,86.0,88.0,88.0,101.0,60.0
547,Nodulithe,Roggenrola,524,/images/thumb/2/2d/Nodulithe-NB.png/250px-Nodu...,/images/7/7e/Cri_0524_HOME.ogg,Roche,NaN,"0,4","18,0",NaN,...,NaN,+1 Déf.,56 exp.,1 059 860 exp.,55.0,75.0,85.0,85.0,25.0,15.0
525,Brutapode,Scolipede,545,/images/thumb/f/f1/Brutapode-NB.png/250px-Brut...,/images/5/56/Cri_0545_HOME.ogg,Insecte,Poison,"2,5","200,5",NaN,...,NaN,+3 Vit.,214 exp.,1 059 860 exp.,60.0,100.0,89.0,89.0,69.0,112.0
519,Bargantua,Basculin,550,/images/thumb/f/fa/Bargantua_%28Motif_Blanc%29...,/images/e/e6/Cri_0550_HOME.ogg,Eau,NaN,"1,0","18,0",NaN,...,NaN,+2 Vit.,161 exp.,1 000 000 exp.,NaN,92.0,65.0,65.0,55.0,98.0
455,Lugulabre,Chandelure,609,/images/thumb/d/d2/Lugulabre-NB.png/250px-Lugu...,/images/8/84/Cri_0609_HOME.ogg,Spectre,Feu,"1,0","34,3",NaN,...,NaN,+3 Att. Spé,234 exp.,1 059 860 exp.,60.0,55.0,90.0,90.0,90.0,80.0
421,Boréas,Tornadus,641,/images/thumb/1/1b/Bor%C3%A9as_%28Forme_Avatar...,/images/6/62/Cri_0641_HOME.ogg,Vol,NaN,NaN,"63,0",NaN,...,NaN,+3 Att. Spé,261 exp.,1 250 000 exp.,79.0,115.0,70.0,70.0,80.0,111.0
420,Fulguris,Thundurus,642,/images/thumb/1/1b/Fulguris_%28Forme_Avatar%29...,/images/c/ce/Cri_0642_HOME.ogg,Électrik,Vol,NaN,"61,0",NaN,...,NaN,+3 Att. Spé,261 exp.,1 250 000 exp.,79.0,115.0,70.0,70.0,80.0,111.0
417,Démétéros,Landorus,645,/images/thumb/8/87/D%C3%A9m%C3%A9t%C3%A9ros_%2...,/images/f/ff/Cri_0645_HOME.ogg,Sol,Vol,NaN,"68,0",NaN,...,NaN,+3 Att.,270 exp.,1 250 000 exp.,89.0,125.0,90.0,90.0,80.0,101.0
402,Amphinobi,Greninja,658,/images/thumb/7/75/Amphinobi-XY.png/250px-Amph...,/images/9/9c/Cri_0658_HOME.ogg,Eau,Ténèbres,"1,5","40,0",NaN,...,NaN,+3 Vitesse,239 exp.,1 059 860 exp.,72.0,95.0,67.0,67.0,71.0,122.0
391,Mistigrix,Meowstic,678,/images/thumb/5/57/Mistigrix_%28Femelle%29-XY....,/images/f/fa/Cri_0678_HOME.ogg,Psy,NaN,"0,6","8,5",NaN,...,NaN,+2 Vitesse,163 exp.,1 000 000 exp.,74.0,48.0,76.0,76.0,81.0,104.0
325,Rocabot,Rockruff,744,/images/thumb/b/b0/Rocabot-SL.png/250px-Rocabo...,/images/1/1a/Cri_0744_HOME.ogg,Roche,NaN,"0,5","9,2",NaN,...,NaN,+1 Attaque,56 exp.,1 000 000 exp.,45.0,65.0,40.0,40.0,40.0,60.0
324,Lougaroc,Lycanroc,745,/images/thumb/6/63/Lougaroc_%28Forme_Diurne%29...,/images/5/52/Cri_0745_Diurne_HOME.ogg,Roche,NaN,NaN,"25,0",NaN,...,NaN,+2 Attaque,170 exp.,1 000 000 exp.,75.0,115.0,65.0,65.0,65.0,112.0
214,Salarsen Gigamax,Gigantamax Toxtricity,849,/images/thumb/1/16/Salarsen_%28Gigamax%29-EB.p...,/images/7/77/Cri_0849_Gigamax_HOME.ogg,Électrik,Poison,"24,0","???,?",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,Salarsen,Toxtricity,849,/images/thumb/a/ad/Salarsen_%28Forme_Aig%C3%BC...,/images/f/f1/Cri_0849_Aig%C3%BCe_HOME.ogg,Électrik,Poison,"1,6","40,0",NaN,...,NaN,+2 Att. Spé,176 exp.,1 059 860 exp.,75.0,98.0,70.0,70.0,70.0,75.0
183,Wimessir,Indeedee,876,/images/thumb/5/5b/Wimessir_%28M%C3%A2le%29-EB...,/images/d/de/Cri_0876_%E2%99%82_HOME.ogg,Psy,Normal,"0,9","28,0",NaN,...,NaN,NaN,166 exp.,800 000 exp.,60.0,65.0,55.0,55.0,95.0,95.0
153,Amovénus,Enamorus,905,/images/thumb/9/9f/Amov%C3%A9nus_%28Forme_Avat...,/images/e/e6/Cri_0905_HOME.ogg,Fée,Vol,"1,6","48,0",NaN,...,NaN,+3 Att. Spé,116 exp.,1 250 000 exp.,74.0,115.0,70.0,70.0,80.0,106.0
142,Fragroin,Oinkologne,916,/images/thumb/a/a0/Fragroin_%28Femelle%29-EV.p...,/images/6/64/Cri_0916_%E2%99%82_HOME.ogg,Normal,NaN,"1,0","120,0",NaN,...,NaN,+2 PV,171 exp.,1 000 000 exp.,110.0,100.0,75.0,75.0,80.0,65.0
130,Tapatoès,Squawkabilly,931,/images/thumb/b/b1/Tapato%C3%A8s_%28Plumage_Ve...,/images/b/bb/Cri_0931_HOME.ogg,Normal,Vol,"0,6","2,4",NaN,...,NaN,+1 Attaque,146 exp.,600 000 exp.,82.0,96.0,51.0,51.0,51.0,92.0
50,Ogerpon,Ogerpon,1017,/images/thumb/8/82/Ogerpon_%28Masque_Turquoise...,/images/a/a5/Cri_1017_HOME.ogg,Bipède,NaN,"1,2","39,8",NaN,...,NaN,NaN,NaN,NaN,80.0,120.0,84.0,84.0,96.0,110.0

In [5]:
dft = df

In [6]:
dft.num_pokedex.unique().value_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [ ]:
import pandas as pd

# Exemple de DataFrame
dfi = pd.DataFrame({
    'nom_pkmn': ['Pikachu', 'Lougaroc', 'Dracaufeu'],
    'type': ['Électrik', 'Roche', 'Feu/Vol']
})

# Dupliquer la ligne de Dracaufeu en une seule ligne
dfi.loc[len(dfi)] = dfi.loc[dfi.loc[dfi.nom_pkmn == 'Lougaroc'].index[0]]

# Modifier la nouvelle ligne dupliquée
dfi.loc[len(dfi)-1, 'nom_pkmn'] += ' (Diurne)'

print(dfi)

            nom_pkmn      type
0            Pikachu  Électrik
1           Lougaroc     Roche
2          Dracaufeu   Feu/Vol
3  Lougaroc (Diurne)     Roche

In [ ]:
dft.loc[len(df)] = {'nom_pkmn':'Boréas (Totémique)', 'nom_pkmn_us':'Tornadus (Therian)', 'num_pokedex':641, 'url_image':'/images/thumb/a/a1/Boréas_%28Forme_Totémique%29-N2B2.png/150px-Boréas_%28Forme_Totémique%29-N2B2.png', 'type_1':'Vol', 'type_2':None, 'taille_m':1.4, 'poids':63.0, 'talent_1':'Régé-Force', 'talent_2':None, 'talent_cache':None, 'sexe':'0 % femelle; 100 % mâle', 'taux_de_capture':3, 'cycle_eclosion':120, 'groupe_oeuf_1':'Inconnu', 'groupe_oeuf_2':None, 'points_effort':'+3 Att. Spé', 'points_exp':'261 exp.', 'exp_niv100':'1 250 000 exp', 'pv':79, 'attaque':100, 'defense':80, 'attaque_speciale':110, 'defense_speciale':90, 'vitesse':121}

In [ ]:
dft.tail()

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
1146,Méga-Florizarre,Mega Venusaur,3,/images/thumb/1/13/M%C3%A9ga-Florizarre-XY.png...,/images/e/e6/Cri_0003_M%C3%A9ga_HOME.ogg,Plante,Poison,"2,4","155,5",Isograisse,...,NaN,NaN,NaN,NaN,80.0,100.0,123.0,123.0,120.0,80.0
1147,Florizarre Gigamax,Gigantamax Venusaur,3,/images/thumb/2/2e/Florizarre_%28Gigamax%29-EB...,/images/1/10/Cri_0003_Gigamax_HOME.ogg,Plante,Poison,"24,0","???,?",Engrais,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1148,Florizarre,Venusaur,3,/images/thumb/4/42/Florizarre-RFVF.png/250px-F...,/images/3/36/Cri_0003_DP.ogg,Plante,Poison,"2,0","100,0",Engrais,...,Végétal,+2 Att. Spé ; +1 Déf. Spé,236 exp. (208 (Première à quatrième génération)),1 059 860 exp.,80.0,82.0,83.0,83.0,100.0,80.0
1149,Herbizarre,Ivysaur,2,/images/thumb/4/44/Herbizarre-RFVF.png/250px-H...,/images/4/43/Cri_0002_DP.ogg,Plante,Poison,"1,0","13,0",Engrais,...,Végétal,+1 Att. Spé ; +1 Déf. Spé,141 exp.,1 059 860 exp.,60.0,62.0,63.0,63.0,80.0,60.0
1150,Boréas (Totémique),Tornadus (Therian),641,/images/thumb/a/a1/Boréas_%28Forme_Totémique%2...,NaN,Vol,None,1.4,NaN,Régé-Force,...,None,+3 Att. Spé,261 exp.,1 250 000 exp,79.0,100.0,110.0,80.0,90.0,121.0

In [ ]:
df.columns

Index(['nom_pkmn', 'nom_pkmn_us', 'num_pokedex', 'url_image', 'url_cri',
       'type_1', 'type_2', 'taille_m', 'poids_kg', 'talent_1', 'talent_2',
       'talent_cache', 'sexe', 'taux_de_capture', 'cycle_eclosion',
       'groupe_oeuf_1', 'groupe_oeuf_2', 'points_effort', 'points_exp',
       'exp_niv100', 'pv', 'attaque', 'attaque_speciale', 'defense',
       'defense_speciale', 'vitesse'],
      dtype='object')

In [ ]:
dft.loc[df.nom_pkmn == 'Caninos','talent_1'] = 'Intimidation'

In [ ]:
dft[dft.talent_1.isna()].sort_values(by='num_pokedex')

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
1058,Gravalanch,Graveler,75,/images/thumb/a/a5/Gravalanch-RFVF.png/250px-G...,/images/4/4a/Cri_0075_HOME.ogg,Roche,Sol,"1,0","105,0",NaN,...,NaN,+2 Déf.,134 exp.,1 059 860 exp.,55.0,95.0,115.0,115.0,45.0,35.0
810,Tengalice,Shiftry,275,/images/thumb/d/d2/Tengalice-RS.png/250px-Teng...,/images/1/1d/Cri_0275_HOME.ogg,Plante,Ténèbres,"1,3","59,6",NaN,...,Végétal,+3 Att.,181 exp.,1 059 860 exp.,90.0,100.0,60.0,60.0,60.0,80.0
675,Tiplouf,Piplup,393,/images/thumb/c/c2/Tiplouf-DEPS.png/250px-Tipl...,/images/8/84/Cri_0393_HOME.ogg,Eau,NaN,"0,4","5,2",NaN,...,Terrestre,+1 Att. Spé,66 exp.,1 059 860 exp.,53.0,51.0,53.0,53.0,56.0,40.0
674,Prinplouf,Prinplup,394,/images/thumb/c/c5/Prinplouf-DEPS.png/250px-Pr...,/images/2/27/Cri_0394_HOME.ogg,Eau,NaN,"0,8","23,0",NaN,...,Terrestre,+2 Att. Spé,143 exp.,1 059 860 exp.,64.0,66.0,68.0,68.0,76.0,50.0
673,Pingoléon,Empoleon,395,/images/thumb/1/14/Pingol%C3%A9on-DEPS.png/250...,/images/9/95/Cri_0395_HOME.ogg,Eau,Acier,"1,7","84,5",NaN,...,Terrestre,+3 Att. Spé,210 exp.,1 059 860 exp.,84.0,86.0,88.0,88.0,101.0,60.0
547,Nodulithe,Roggenrola,524,/images/thumb/2/2d/Nodulithe-NB.png/250px-Nodu...,/images/7/7e/Cri_0524_HOME.ogg,Roche,NaN,"0,4","18,0",NaN,...,NaN,+1 Déf.,56 exp.,1 059 860 exp.,55.0,75.0,85.0,85.0,25.0,15.0
525,Brutapode,Scolipede,545,/images/thumb/f/f1/Brutapode-NB.png/250px-Brut...,/images/5/56/Cri_0545_HOME.ogg,Insecte,Poison,"2,5","200,5",NaN,...,NaN,+3 Vit.,214 exp.,1 059 860 exp.,60.0,100.0,89.0,89.0,69.0,112.0
519,Bargantua,Basculin,550,/images/thumb/f/fa/Bargantua_%28Motif_Blanc%29...,/images/e/e6/Cri_0550_HOME.ogg,Eau,NaN,"1,0","18,0",NaN,...,NaN,+2 Vit.,161 exp.,1 000 000 exp.,NaN,92.0,65.0,65.0,55.0,98.0
455,Lugulabre,Chandelure,609,/images/thumb/d/d2/Lugulabre-NB.png/250px-Lugu...,/images/8/84/Cri_0609_HOME.ogg,Spectre,Feu,"1,0","34,3",NaN,...,NaN,+3 Att. Spé,234 exp.,1 059 860 exp.,60.0,55.0,90.0,90.0,90.0,80.0
421,Boréas,Tornadus,641,/images/thumb/1/1b/Bor%C3%A9as_%28Forme_Avatar...,/images/6/62/Cri_0641_HOME.ogg,Vol,NaN,NaN,"63,0",NaN,...,NaN,+3 Att. Spé,261 exp.,1 250 000 exp.,79.0,115.0,70.0,70.0,80.0,111.0
420,Fulguris,Thundurus,642,/images/thumb/1/1b/Fulguris_%28Forme_Avatar%29...,/images/c/ce/Cri_0642_HOME.ogg,Électrik,Vol,NaN,"61,0",NaN,...,NaN,+3 Att. Spé,261 exp.,1 250 000 exp.,79.0,115.0,70.0,70.0,80.0,111.0
417,Démétéros,Landorus,645,/images/thumb/8/87/D%C3%A9m%C3%A9t%C3%A9ros_%2...,/images/f/ff/Cri_0645_HOME.ogg,Sol,Vol,NaN,"68,0",NaN,...,NaN,+3 Att.,270 exp.,1 250 000 exp.,89.0,125.0,90.0,90.0,80.0,101.0
402,Amphinobi,Greninja,658,/images/thumb/7/75/Amphinobi-XY.png/250px-Amph...,/images/9/9c/Cri_0658_HOME.ogg,Eau,Ténèbres,"1,5","40,0",NaN,...,NaN,+3 Vitesse,239 exp.,1 059 860 exp.,72.0,95.0,67.0,67.0,71.0,122.0
391,Mistigrix,Meowstic,678,/images/thumb/5/57/Mistigrix_%28Femelle%29-XY....,/images/f/fa/Cri_0678_HOME.ogg,Psy,NaN,"0,6","8,5",NaN,...,NaN,+2 Vitesse,163 exp.,1 000 000 exp.,74.0,48.0,76.0,76.0,81.0,104.0
325,Rocabot,Rockruff,744,/images/thumb/b/b0/Rocabot-SL.png/250px-Rocabo...,/images/1/1a/Cri_0744_HOME.ogg,Roche,NaN,"0,5","9,2",NaN,...,NaN,+1 Attaque,56 exp.,1 000 000 exp.,45.0,65.0,40.0,40.0,40.0,60.0
324,Lougaroc,Lycanroc,745,/images/thumb/6/63/Lougaroc_%28Forme_Diurne%29...,/images/5/52/Cri_0745_Diurne_HOME.ogg,Roche,NaN,NaN,"25,0",NaN,...,NaN,+2 Attaque,170 exp.,1 000 000 exp.,75.0,115.0,65.0,65.0,65.0,112.0
214,Salarsen Gigamax,Gigantamax Toxtricity,849,/images/thumb/1/16/Salarsen_%28Gigamax%29-EB.p...,/images/7/77/Cri_0849_Gigamax_HOME.ogg,Électrik,Poison,"24,0","???,?",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,Salarsen,Toxtricity,849,/images/thumb/a/ad/Salarsen_%28Forme_Aig%C3%BC...,/images/f/f1/Cri_0849_Aig%C3%BCe_HOME.ogg,Électrik,Poison,"1,6","40,0",NaN,...,NaN,+2 Att. Spé,176 exp.,1 059 860 exp.,75.0,98.0,70.0,70.0,70.0,75.0
183,Wimessir,Indeedee,876,/images/thumb/5/5b/Wimessir_%28M%C3%A2le%29-EB...,/images/d/de/Cri_0876_%E2%99%82_HOME.ogg,Psy,Normal,"0,9","28,0",NaN,...,NaN,NaN,166 exp.,800 000 exp.,60.0,65.0,55.0,55.0,95.0,95.0
153,Amovénus,Enamorus,905,/images/thumb/9/9f/Amov%C3%A9nus_%28Forme_Avat...,/images/e/e6/Cri_0905_HOME.ogg,Fée,Vol,"1,6","48,0",NaN,...,NaN,+3 Att. Spé,116 exp.,1 250 000 exp.,74.0,115.0,70.0,70.0,80.0,106.0
142,Fragroin,Oinkologne,916,/images/thumb/a/a0/Fragroin_%28Femelle%29-EV.p...,/images/6/64/Cri_0916_%E2%99%82_HOME.ogg,Normal,NaN,"1,0","120,0",NaN,...,NaN,+2 PV,171 exp.,1 000 000 exp.,110.0,100.0,75.0,75.0,80.0,65.0
130,Tapatoès,Squawkabilly,931,/images/thumb/b/b1/Tapato%C3%A8s_%28Plumage_Ve...,/images/b/bb/Cri_0931_HOME.ogg,Normal,Vol,"0,6","2,4",NaN,...,NaN,+1 Attaque,146 exp.,600 000 exp.,82.0,96.0,51.0,51.0,51.0,92.0
50,Ogerpon,Ogerpon,1017,/images/thumb/8/82/Ogerpon_%28Masque_Turquoise...,/images/a/a5/Cri_1017_HOME.ogg,Bipède,NaN,"1,2","39,8",NaN,...,NaN,NaN,NaN,NaN,80.0,120.0,84.0,84.0,96.0,110.0

In [ ]:
conn = sqlite3.connect('../../../B___Data/pkmn.db')

In [ ]:
test_response = ['Pokémon', 'type', 'Plante', 'Poison', 'première génération', 'Pokémon de départ', 'région', 'Kanto', 'bulbe', 'capacité', 'Vampigraine', 'Fouet Lianes', 'niveau', 'Herbizarre', 'Florizarre', 'sixième génération', 'méga-évoluer', 'Méga-Florizarre', 'Florizarrite', 'distribué de manière événementielle', 'Sacha', 'Samouraï', 'dessin animé', 'épisode 10', 'épisode 838', 'Arc Rouge, Bleu et Vert', 'chapitre 2', 'Tome 1', 'Rouge', 'chapitre 3', 'chapitre 4', 'chapitre 5', 'chapitre 6', 'chapitre 8', 'chapitre 9', 'chapitre 12', 'chapitre 13', 'Bleu', 'chapitre 15', 'Groundbreakers']

In [ ]:
talents = ['Engrais', 'Chlorophylle', 'talent caché']

In [ ]:
if len(talents) > 1 and 'talent caché' not in talents:
    talent_1 = talents[1]
elif len(talents) > 1 and 'talent caché' in talents:
    talent_cache = talents[-2]

In [ ]:
if len(talents) == 1:
    talent_1 =talents[0]
elif len(talents) == 2 and 'talent caché' not in talents:
    talent_1 = talents[0]
    talent_2 = talents[1]
elif len(talents) == 2 and 'talent caché' in talents:
    talent_1 = talents[0]
    talent_cache = talents[-2]
elif len(talents) == 3:
    talent_1 = talents[0]
    talent_2 = talents[1]
    talent_cache = talents[-2]

In [ ]:
print(talent_1, talent_2, talent_cache)

Engrais Chlorophylle Chlorophylle

In [ ]:
text = R'12.5\xa0% femelle\u202f; 87.5\xa0% mâle'
clean_text = text.replace('\xa0', ' ').replace('\u202f', '')
print(clean_text)

12.5\xa0% femelle\u202f; 87.5\xa0% mâle

In [ ]:
pv, attaque, defense, attaque_speciale, defense_speciale, vitesse = None, None, None, None, None, None

In [ ]:
liste = ['a', '1.5', 'b']

num = [x for x in liste if x[0].isdigit()][0]
num

'1.5'