In [1]:
import pandas as pd, sys, os

In [7]:
if '../..' not in sys.path:
    sys.path.append('../..')

In [21]:
df = pd.read_csv('../../B___Data/CSV/pokemons.csv')

In [18]:
df.head()

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
0,Bulbizarre,Bulbasaur,1,/images/thumb/e/ef/Bulbizarre-RFVF.png/250px-B...,/images/4/49/Cri_0001_XY.ogg,Plante,Poison,"0,7","6,9",Engrais,...,Végétal,+1 Att. Spé,64 exp.,1 059 860 exp.,45.0,49.0,49.0,49.0,65.0,45.0
1,Pikachu,Pikachu,25,/images/thumb/7/76/Pikachu-DEPS.png/250px-Pika...,/images/2/28/Cri_0025_HOME.ogg,Électrik,NaN,"0,4","6,0",Statik,...,Féerique,+2 Vit.,82 exp.,1 000 000 exp.,35.0,55.0,40.0,40.0,50.0,90.0
2,Arbok,Arbok,24,/images/thumb/7/7f/Arbok-RFVF.png/250px-Arbok-...,/images/6/61/Cri_0024_HOME.ogg,Poison,NaN,"3,5","65,0",Intimidation,...,Draconique,+2 Att.,147 exp.,1 000 000 exp.,60.0,95.0,69.0,69.0,79.0,80.0
3,Abo,Ekans,23,/images/thumb/5/56/Abo-RFVF.png/250px-Abo-RFVF...,/images/3/3c/Cri_0023_HOME.ogg,Poison,NaN,"2,0","6,9",Intimidation,...,Draconique,+1 Att.,62 exp.,1 000 000 exp.,35.0,60.0,44.0,44.0,54.0,55.0
4,Rapasdepic,Fearow,22,/images/thumb/f/f2/Rapasdepic-RFVF.png/250px-R...,/images/5/5d/Cri_0022_HOME.ogg,Normal,Vol,"1,2","38,0",Regard Vif,...,NaN,+2 Vit.,162 exp.,1 000 000 exp.,65.0,90.0,65.0,65.0,61.0,100.0

In [19]:
df.url_image = df.url_image.apply(lambda x: '/images'+x.split('/thumb')[1].split('png/')[0]+'png' if '/thumb' in x else x.split('png/')[0]+'png')

In [20]:
df.head()

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
0,Bulbizarre,Bulbasaur,1,/images/e/ef/Bulbizarre-RFVF.png,/images/4/49/Cri_0001_XY.ogg,Plante,Poison,"0,7","6,9",Engrais,...,Végétal,+1 Att. Spé,64 exp.,1 059 860 exp.,45.0,49.0,49.0,49.0,65.0,45.0
1,Pikachu,Pikachu,25,/images/7/76/Pikachu-DEPS.png,/images/2/28/Cri_0025_HOME.ogg,Électrik,NaN,"0,4","6,0",Statik,...,Féerique,+2 Vit.,82 exp.,1 000 000 exp.,35.0,55.0,40.0,40.0,50.0,90.0
2,Arbok,Arbok,24,/images/7/7f/Arbok-RFVF.png,/images/6/61/Cri_0024_HOME.ogg,Poison,NaN,"3,5","65,0",Intimidation,...,Draconique,+2 Att.,147 exp.,1 000 000 exp.,60.0,95.0,69.0,69.0,79.0,80.0
3,Abo,Ekans,23,/images/5/56/Abo-RFVF.png,/images/3/3c/Cri_0023_HOME.ogg,Poison,NaN,"2,0","6,9",Intimidation,...,Draconique,+1 Att.,62 exp.,1 000 000 exp.,35.0,60.0,44.0,44.0,54.0,55.0
4,Rapasdepic,Fearow,22,/images/f/f2/Rapasdepic-RFVF.png,/images/5/5d/Cri_0022_HOME.ogg,Normal,Vol,"1,2","38,0",Regard Vif,...,NaN,+2 Vit.,162 exp.,1 000 000 exp.,65.0,90.0,65.0,65.0,61.0,100.0

In [8]:
from B___Data.database import Database
from B___Data.pokemon import Pokemon

In [24]:
db = Database('../../B___Data/tests_pkmn.db')
db.count('Pokemons')

1150

In [13]:
Pokemon(db, 'Papilusion').play_sound()

In [23]:
df = pd.read_csv('../../B___Data/CSV/pokemons.csv')

In [ ]:
df

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
0,Bulbizarre,Bulbasaur,1,/images/thumb/e/ef/Bulbizarre-RFVF.png/250px-B...,/images/4/49/Cri_0001_XY.ogg,Plante,Poison,"0,7","6,9",Engrais,...,Végétal,+1 Att. Spé,64 exp.,1 059 860 exp.,45.0,49.0,49.0,49.0,65.0,45.0
1,Pikachu,Pikachu,25,/images/thumb/7/76/Pikachu-DEPS.png/250px-Pika...,/images/2/28/Cri_0025_HOME.ogg,Électrik,NaN,"0,4","6,0",Statik,...,Féerique,+2 Vit.,82 exp.,1 000 000 exp.,35.0,55.0,40.0,40.0,50.0,90.0
2,Arbok,Arbok,24,/images/thumb/7/7f/Arbok-RFVF.png/250px-Arbok-...,/images/6/61/Cri_0024_HOME.ogg,Poison,NaN,"3,5","65,0",Intimidation,...,Draconique,+2 Att.,147 exp.,1 000 000 exp.,60.0,95.0,69.0,69.0,79.0,80.0
3,Abo,Ekans,23,/images/thumb/5/56/Abo-RFVF.png/250px-Abo-RFVF...,/images/3/3c/Cri_0023_HOME.ogg,Poison,NaN,"2,0","6,9",Intimidation,...,Draconique,+1 Att.,62 exp.,1 000 000 exp.,35.0,60.0,44.0,44.0,54.0,55.0
4,Rapasdepic,Fearow,22,/images/thumb/f/f2/Rapasdepic-RFVF.png/250px-R...,/images/5/5d/Cri_0022_HOME.ogg,Normal,Vol,"1,2","38,0",Regard Vif,...,NaN,+2 Vit.,162 exp.,1 000 000 exp.,65.0,90.0,65.0,65.0,61.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,Salamèche,Charmander,4,/images/thumb/8/89/Salam%C3%A8che-RFVF.png/250...,/images/d/d9/Cri_0004_DP.ogg,Feu,NaN,"0,6","8,5",Brasier,...,Monstrueux,+1 Vit.,65 exp.,1 059 860 exp.,39.0,52.0,43.0,43.0,50.0,65.0
1146,Méga-Florizarre,Mega Venusaur,3,/images/thumb/1/13/M%C3%A9ga-Florizarre-XY.png...,/images/e/e6/Cri_0003_M%C3%A9ga_HOME.ogg,Plante,Poison,"2,4","155,5",Isograisse,...,NaN,NaN,NaN,NaN,80.0,100.0,123.0,123.0,120.0,80.0
1147,Florizarre Gigamax,Gigantamax Venusaur,3,/images/thumb/2/2e/Florizarre_%28Gigamax%29-EB...,/images/1/10/Cri_0003_Gigamax_HOME.ogg,Plante,Poison,"24,0","???,?",Engrais,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1148,Florizarre,Venusaur,3,/images/thumb/4/42/Florizarre-RFVF.png/250px-F...,/images/3/36/Cri_0003_DP.ogg,Plante,Poison,"2,0","100,0",Engrais,...,Végétal,+2 Att. Spé ; +1 Déf. Spé,236 exp. (208 (Première à quatrième génération)),1 059 860 exp.,80.0,82.0,83.0,83.0,100.0,80.0
1149,Herbizarre,Ivysaur,2,/images/thumb/4/44/Herbizarre-RFVF.png/250px-H...,/images/4/43/Cri_0002_DP.ogg,Plante,Poison,"1,0","13,0",Engrais,...,Végétal,+1 Att. Spé ; +1 Déf. Spé,141 exp.,1 059 860 exp.,60.0,62.0,63.0,63.0,80.0,60.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1150 entries, 0 to 1149
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nom_pkmn          1150 non-null   object
 1   nom_pkmn_us       1150 non-null   object
 2   num_pokedex       1150 non-null   int64
 3   url_image         1150 non-null   object
 4   url_cri           1150 non-null   object
 5   type_1            1150 non-null   object
 6   type_2            620 non-null    object
 7   taille_m          1145 non-null   object
 8   poids_kg          1150 non-null   object
 9   talent_1          1126 non-null   object
 10  talent_2          568 non-null    object
 11  talent_cache      898 non-null    object
 12  sexe              1150 non-null   object
 13  taux_de_capture   1036 non-null   float64
 14  cycle_eclosion    1037 non-null   float64
 15  groupe_oeuf_1     1037 non-null   object
 16  groupe_oeuf_2     286 non-null    object
 17  points_effort     1035 non-null   object
 18  points_exp        1037 non-null   object
 19  exp_niv100        1037 non-null   object
 20  pv                1117 non-null   float64
 21  attaque           1115 non-null   float64
 22  attaque_speciale  1115 non-null   float64
 23  defense           1115 non-null   float64
 24  defense_speciale  1119 non-null   float64
 25  vitesse           1119 non-null   float64
dtypes: float64(8), int64(1), object(17)
memory usage: 233.7+ KB

Vérification des pokemon manquants par leur numéro :

In [ ]:
print(sorted(set(range(1, df['num_pokedex'].max() + 1)) - set(df['num_pokedex']))) # Regarde quels numéros ne sont pas présent dans le dataset

[483, 484, 487, 492, 710, 711, 718, 720, 746, 774, 888, 889, 901, 925, 964, 982, 999, 1024]

In [ ]:
### N.1024 Terapagos
#Forme Normal
df.loc[len(df)] = [
       'Terapagos (Normale)', 'Terapagos (Normal)', 1024,
       '/images/1/15/Terapagos_%28Forme_Normale%29-EV.png', 
       '/images/9/90/Cri_1024_HOME.ogg',
       'Normal', None, 
       0.2, 6.5, 
       'Téramorphose', None, None,
       '50 % femelle ; 50 % mâle', 255, None,
       'Inconnu', None, '+1 Défense', None, '1 250 000 exp.', 
       90, 65, 85, 65, 85, 60]
#Forme Téracristal
df.loc[len(df)] = [df.nom_pkmn == 'Terapagos (Normale)'].assign(nom_pkmn='Terapagos (Téracristal)',nom_pkmn_us='Terapagos (Terastal)')
df.loc[len(df)-1, ['url_image', 'taille_m', 'poids_kg', 'talent_1',
       'pv', 'attaque', 'defense', 'attaque_speciale', 'defense_speciale', 'vitesse']] = [
       '/images/d/d4/Terapagos_%28Forme_Téracristal%29-EV.png',
       0.3, 16.0,
       'Téra-carapace',
       95, 95, 110, 105, 110, 85
] 
#Forme Stellaire
df.loc[len(df)] = [df.nom_pkmn == 'Terapagos (Normale)'].assign(nom_pkmn='Terapagos (Stellaire)',nom_pkmn_us='Terapagos (Stellar)')
df.loc[len(df)-1, ['url_image', 'taille_m', 'poids_kg', 'talent_1',
       'pv', 'attaque', 'defense', 'attaque_speciale', 'defense_speciale', 'vitesse']] = [
       '/images/3/37/Sprite_1024_Stellaire_HOME.png',
       1.7, 77.0,
       'Téraformation 0',
       160, 105, 110, 130, 110, 85
       ]