In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('../../B___Data/CSV/pokemons.csv')

In [44]:
df.loc[len(df)] = [
    'Dialga (Normale)', 'Dialga (Normal)', 483, 
    '/images/e/e4/Dialga-DEPS.png', 
    '/images/0/0d/Cri_0483_HOME.ogg', 
    'Acier', 'Dragon', 
    5.4, 683.0, 
    'Pression', None, 'Télépathe', 
    'Asexué', 3, 120, 'Inconnu', None, '+3 Att. Spé', '220 Exp.', '1 250 000 exp', 
    100, 100, 120, 150, 120, 90
]

In [32]:
data = pd.DataFrame({
    'nom_pkmn': ['Abo', 'Pikachu'],
    'url_image': ['/images/abo.png', '/images/pikachu.png'],
    'type_1': ['Poison', 'Electric'],
    'taille_m': [2.0, 0.4],
    'poids_kg': [7.0, 6.0]
})

In [40]:
raichu = df.loc[df.nom_pkmn == 'Pikachu'].assign(nom_pkmn = 'Raichu')
data = pd.concat([data, raichu], ignore_index=True)

In [41]:
data

,nom_pkmn,url_image,type_1,taille_m,poids_kg,nom_pkmn_us,num_pokedex,url_cri,type_2,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
0,Abo,/images/abo.png,Poison,2.0,7.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Pikachu,/images/pikachu.png,Electric,0.4,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Raichu,/images/thumb/7/76/Pikachu-DEPS.png/250px-Pika...,Électrik,"0,4","6,0",Pikachu,25.0,/images/2/28/Cri_0025_HOME.ogg,NaN,Statik,...,Féerique,+2 Vit.,82 exp.,1 000 000 exp.,35.0,55.0,40.0,40.0,50.0,90.0

In [ ]:
df = pd.

,nom_pkmn,nom_pkmn_us,num_pokedex,url_image,url_cri,type_1,type_2,taille_m,poids_kg,talent_1,...,groupe_oeuf_2,points_effort,points_exp,exp_niv100,pv,attaque,attaque_speciale,defense,defense_speciale,vitesse
984,Tauros,Tauros,128,/images/thumb/4/48/Tauros-RFVF.png/250px-Tauro...,/images/c/c2/Cri_0128_HOME.ogg,Normal,NaN,"1,4","88,4",Intimidation,...,NaN,+1 Att. ; +1 Vit.,211 exp.,1 250 000 exp.,75.0,100.0,95.0,95.0,70.0,110.0

In [ ]:
df.loc[df.nom_pkmn_us == 'Test']

Empty DataFrame
Columns: [nom_pkmn, nom_pkmn_us, num_pokedex, url_image, url_cri, type_1, type_2, taille_m, poids_kg, talent_1, talent_2, talent_cache, sexe, taux_de_capture, cycle_eclosion, groupe_oeuf_1, groupe_oeuf_2, points_effort, points_exp, exp_niv100, pv, attaque, attaque_speciale, defense, defense_speciale, vitesse]
Index: []

[0 rows x 26 columns]

Vérification des pokemon manquants par leur numéro :

In [ ]:
### N. 000 nom_pkmn
# df.loc[len(df)] = ['Banshitrouye', 'nom_pkmn_us', 'num_pokedex', 'url_image', 'url_cri',
#        'type_1', 'type_2', 'taille_m', 'poids_kg', 'talent_1', 'talent_2',
#        'talent_cache', 'sexe', 'taux_de_capture', 'cycle_eclosion',
#        'groupe_oeuf_1', 'groupe_oeuf_2', 'points_effort', 'points_exp',
#        'exp_niv100', 'pv', 'attaque', 'attaque_speciale', 'defense',
#        'defense_speciale', 'vitesse']
       
# df.loc[len(df)] = [df.nom_pkmn == 'Hoopa'].assign(nom_pkmn='nom_pkmn_2',nom_pkmn_us='nom_pkmn_us_2')
# df.loc[len(df)-1, ["columns that change"]] = [
#     "new valors"
# ]

In [ ]:
df.url_image

0       /images/thumb/e/ef/Bulbizarre-RFVF.png/250px-B...
1       /images/thumb/5/51/Rattatac_d%27Alola-SL.png/2...
2       /images/thumb/9/98/Rattatac-RFVF.png/250px-Rat...
3       /images/thumb/c/cb/Rattata_d%27Alola-SL.png/25...
4       /images/thumb/9/9e/Rattata-RFVF.png/250px-Ratt...
                              ...
1145    /images/thumb/8/89/Salam%C3%A8che-RFVF.png/250...
1146    /images/thumb/1/13/M%C3%A9ga-Florizarre-XY.png...
1147    /images/thumb/2/2e/Florizarre_%28Gigamax%29-EB...
1148    /images/thumb/4/42/Florizarre-RFVF.png/250px-F...
1149    /images/thumb/4/44/Herbizarre-RFVF.png/250px-H...
Name: url_image, Length: 1150, dtype: object

In [ ]:
df.url_image = df.url_image.apply(lambda x: '/images'+x.split('/thumb')[1].split('png/')[0]+'png' if '/thumb' in x else x.split('png/')[0]+'png')

In [ ]:
df.url_image

0                   /images/e/ef/Bulbizarre-RFVF.png
1             /images/5/51/Rattatac_d%27Alola-SL.png
2                     /images/9/98/Rattatac-RFVF.png
3              /images/c/cb/Rattata_d%27Alola-SL.png
4                      /images/9/9e/Rattata-RFVF.png
                            ...
1145            /images/8/89/Salam%C3%A8che-RFVF.png
1146        /images/1/13/M%C3%A9ga-Florizarre-XY.png
1147    /images/2/2e/Florizarre_%28Gigamax%29-EB.png
1148                /images/4/42/Florizarre-RFVF.png
1149                /images/4/44/Herbizarre-RFVF.png
Name: url_image, Length: 1150, dtype: object

In [ ]:
data = pd.DataFrame({
    'url_image': [
        '/images/thumb/5/5c/Mime_Jr.-DP.png/250px-Mime_Jr.-DP.png',
        '/images/thumb/4/47/Mimantis-SL.png/250px-Mimantis-SL.png',
        '/images/thumb/c/cb/Miasmax-NB.png/250px-Miasmax-NB.png'
    ]
})
data

                                           url_image
0  /images/thumb/5/5c/Mime_Jr.-DP.png/250px-Mime_...
1  /images/thumb/4/47/Mimantis-SL.png/250px-Miman...
2  /images/thumb/c/cb/Miasmax-NB.png/250px-Miasma...

In [ ]:
data.url_image = data.url_image.apply(lambda x: '/images'+(x.split('thumb')[1]).split('png/')[0]+'png')

In [ ]:
data

                      url_image
0  /images/5/5c/Mime_Jr.-DP.png
1  /images/4/47/Mimantis-SL.png
2   /images/c/cb/Miasmax-NB.png